In [3]:
import pandas as pd
data={
    'Temperature':['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
    'Colour':['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
    'Target':[1,1,1,0,1,0,1,0,1,1]
}

In [2]:
df=pd.DataFrame(data)
df.head()

  Temperature  Colour  Target
0         Hot     Red       1
1        Cold  Yellow       1
2    Very Hot    Blue       1
3        Warm    Blue       0
4         Hot     Red       1

In [4]:
from feature_engine.encoding import MeanEncoder
encoder=MeanEncoder(variables=['Temperature','Colour'])
df_encoded=encoder.fit_transform(df,df['Target'])

In [5]:
df_encoded

   Temperature  Colour  Target
0     0.750000     1.0       1
1     1.000000     0.6       1
2     1.000000     0.5       1
3     0.333333     0.5       0
4     0.750000     1.0       1
5     0.333333     0.6       0
6     0.333333     1.0       1
7     0.750000     0.6       0
8     0.750000     0.6       1
9     1.000000     0.6       1