In [25]:
import pandas as pd
import numpy as np
df=pd.read_csv('customer.csv')
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [26]:
df.shape

(50, 5)

In [27]:
df=df.iloc[:,2:]

In [28]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['review','education']],df['purchased'],train_size=0.8)

In [30]:
x_train.head()

     review education
31     Poor    School
36     Good        UG
29  Average        UG
24  Average        PG
18     Good    School

In [31]:
x_train.shape

(40, 2)

In [32]:
x_test.shape

(10, 2)

In [33]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [34]:
x_train=oe.transform(x_train)
x_test=oe.transform(x_test)

In [35]:
x_train

array([[0., 0.],
       [2., 1.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [2., 1.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [0., 1.]])

In [36]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [37]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [38]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [39]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [40]:
y_train

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1])